//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class Program {
        
        
	 public List<dynamic> QueryFire(List<dynamic> data) 
	{
		 try {
			 var result = data.Where( e => int.Parse(e.Salary) < 34000 ).Select( e => e.Ename).Cast<dynamic>().ToList();
			 return result ;
		 }
		 catch(Exception ex) 
		 { 
			 return new List<dynamic>{ex.Message + ex.StackTrace}; 
		 } 
	 } 


        public static void Main() {
        }
    }
}
